// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DatabaseExists() {
  return window['go']['main']['App']['DatabaseExists']();
}

export function DoEvents() {
  return window['go']['main']['App']['DoEvents']();
}

export function GetAnime(arg1) {
  return window['go']['main']['App']['GetAnime'](arg1);
}

export function GetAnimes(arg1) {
  return window['go']['main']['App']['GetAnimes'](arg1);
}
