// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DatabaseExists():Promise<boolean>;

export function DoEvents():Promise<void>;

export function GetAnime(arg1:string):Promise<main.AnimeItem>;

export function GetAnimes(arg1:string):Promise<Array<main.AnimeItem>>;
