// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DoEvents():Promise<void>;

export function GetAnimes(arg1:string):Promise<Array<main.AnimeItem>>;
